name: Terraform Deploy

on:
  push:
    paths:
      - 'infra/**'  # 只触发 infra 目录下的文件变化
  pull_request:
    paths:
      - 'infra/**'  # 当 PR 提交 infra 目录的改动时，触发执行

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境运行

    defaults:
      run:
        working-directory: ./infra  # Terraform 配置文件的目录

    steps:
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # 使用 Terraform 最新版本

      # Run Terraform init
      - name: Terraform Init
        run: terraform init

      # Run Terraform plan (optional)
      - name: Terraform Plan
        run: terraform plan

      # Run Terraform apply (auto approve)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # 只在主分支上触发
        run: terraform apply -auto-approve
